// spicejar — Product Data
// Premium Indian Spices & Wellness Herbs
// All data is mock — will be replaced with Medusa/backend API calls

export const products = [
  // ===== EXISTING PRODUCTS (Updated) =====
  {
    id: "prod_01",
    handle: "laal-ras",
    name: "LAAL RAS",
    subtitle: "Kashmiri Red Chilli Powder",
    category: "Ground Spices",
    price: 349,
    comparePrice: 449,
    currency: "INR",
    description:
      "Hand-ground from sun-dried Kashmiri Mathania chillies, LAAL RAS brings a vibrant crimson hue and a warm, smoky depth to every dish. Each jar captures the fiery soul of Kashmir — mild heat, rich colour, and an aroma that transforms curries, marinades, and tandoori preparations into something extraordinary.",
    images: {
      jar: "/images/products/laal-ras.png",
      pouch: "/images/products/laal-ras-pouch.png",
    },
    image: "/images/products/laal-ras.png",
    variants: [
      { id: "var_01_jar_sm", label: "Jar · 50g", price: 199, packaging: "jar" },
      { id: "var_01_jar_md", label: "Jar · 100g", price: 349, packaging: "jar" },
      { id: "var_01_jar_lg", label: "Jar · 250g", price: 749, packaging: "jar" },
      { id: "var_01_pouch_sm", label: "Pouch · 50g", price: 119, packaging: "pouch" },
      { id: "var_01_pouch_md", label: "Pouch · 100g", price: 199, packaging: "pouch" },
      { id: "var_01_pouch_lg", label: "Pouch · 250g", price: 449, packaging: "pouch" },
    ],
    origin: "Kashmir Valley, India",
    usage:
      "Perfect for curries, tandoori marinades, biryanis, and as a finishing garnish. Use 1-2 teaspoons per dish for a vibrant colour and gentle warmth.",
    storage:
      "Store in a cool, dry place away from direct sunlight. Reseal the jar tightly after each use to preserve freshness and colour.",
    tags: ["new", "bestseller"],
    weight: "100g",
  },
  {
    id: "prod_02",
    handle: "haldi-gold",
    name: "HALDI GOLD",
    subtitle: "Lakadong Turmeric Powder",
    category: "Ground Spices",
    price: 399,
    comparePrice: null,
    currency: "INR",
    description:
      "Sourced from the high-altitude Lakadong region of Meghalaya, HALDI GOLD contains up to 9% curcumin — nearly double the average. This isn't ordinary turmeric. Its deep amber colour and earthy, slightly peppery flavour elevate golden milk, dals, and healing broths to a whole new level of wellness and taste.",
    images: {
      jar: "/images/products/haldi-gold.png",
      pouch: "/images/products/haldi-gold-pouch.png",
    },
    image: "/images/products/haldi-gold.png",
    variants: [
      { id: "var_02_jar_sm", label: "Jar · 50g", price: 229, packaging: "jar" },
      { id: "var_02_jar_md", label: "Jar · 100g", price: 399, packaging: "jar" },
      { id: "var_02_jar_lg", label: "Jar · 250g", price: 849, packaging: "jar" },
      { id: "var_02_pouch_sm", label: "Pouch · 50g", price: 139, packaging: "pouch" },
      { id: "var_02_pouch_md", label: "Pouch · 100g", price: 229, packaging: "pouch" },
      { id: "var_02_pouch_lg", label: "Pouch · 250g", price: 499, packaging: "pouch" },
    ],
    origin: "Meghalaya, Northeast India",
    usage:
      "Add to golden milk, curries, dals, smoothies, and rice dishes. A pinch of black pepper enhances curcumin absorption by 2000%.",
    storage:
      "Store in an airtight container away from moisture and sunlight. Turmeric can stain — handle with care.",
    tags: ["bestseller"],
    weight: "100g",
  },
  {
    id: "prod_03",
    handle: "kesar-dhaga",
    name: "KESAR DHAGA",
    subtitle: "Pure Kashmiri Saffron Threads",
    category: "Wellness Herbs",
    price: 1299,
    comparePrice: 1599,
    currency: "INR",
    description:
      "Hand-harvested from the saffron fields of Pampore, Kashmir, each thread of KESAR DHAGA is a labor of love — it takes 75,000 flowers to produce a single pound. These Grade-I Mongra saffron threads deliver an intense golden colour, a honeyed floral aroma, and a flavour that is unmistakably luxurious.",
    images: {
      jar: "/images/products/kesar-dhaga.png",
      pouch: null,
    },
    image: "/images/products/kesar-dhaga.png",
    variants: [
      { id: "var_03_jar_sm", label: "Jar · 1g", price: 599, packaging: "jar" },
      { id: "var_03_jar_md", label: "Jar · 2g", price: 1099, packaging: "jar" },
      { id: "var_03_jar_lg", label: "Jar · 5g", price: 2499, packaging: "jar" },
      { id: "var_03_pouch_sm", label: "Pouch · 1g", price: 499, packaging: "pouch" },
      { id: "var_03_pouch_md", label: "Pouch · 2g", price: 899, packaging: "pouch" },
      { id: "var_03_pouch_lg", label: "Pouch · 5g", price: 1999, packaging: "pouch" },
    ],
    origin: "Pampore, Kashmir",
    usage:
      "Soak 4-5 threads in warm milk for 10 minutes before adding to biryanis, kheer, phirni, or tea. A little goes a long way.",
    storage:
      "Store in the original glass jar in a cool, dark place. Keep away from moisture. Saffron retains potency for up to 3 years when stored correctly.",
    tags: ["premium"],
    weight: "2g",
  },
  {
    id: "prod_04",
    handle: "garam-masala",
    name: "GARAM MASALA",
    subtitle: "Heritage 13-Spice Blend",
    category: "Spice Blends",
    price: 299,
    comparePrice: null,
    currency: "INR",
    description:
      "Our GARAM MASALA is a carefully balanced blend of 13 whole spices — roasted and ground in small batches using a traditional chakki. Black cardamom, cassia bark, cloves, fennel, and mace come together in a warm, aromatic symphony that forms the backbone of North Indian cooking.",
    images: {
      jar: "/images/products/garam-masala.png",
      pouch: "/images/products/garam-masala-pouch.png",
    },
    image: "/images/products/garam-masala.png",
    variants: [
      { id: "var_04_jar_sm", label: "Jar · 50g", price: 169, packaging: "jar" },
      { id: "var_04_jar_md", label: "Jar · 100g", price: 299, packaging: "jar" },
      { id: "var_04_jar_lg", label: "Jar · 250g", price: 649, packaging: "jar" },
      { id: "var_04_pouch_sm", label: "Pouch · 50g", price: 99, packaging: "pouch" },
      { id: "var_04_pouch_md", label: "Pouch · 100g", price: 169, packaging: "pouch" },
      { id: "var_04_pouch_lg", label: "Pouch · 250g", price: 389, packaging: "pouch" },
    ],
    origin: "Lucknow, Uttar Pradesh",
    usage:
      "Add a pinch at the end of cooking for maximum aroma. Perfect for curries, dals, rice dishes, and even sprinkled over roasted vegetables.",
    storage:
      "Store in a cool, dry place. Use within 6 months of opening for best flavour. The glass jar preserves essential oils.",
    tags: ["bestseller"],
    weight: "100g",
  },
  {
    id: "prod_05",
    handle: "elaichi",
    name: "ELAICHI",
    subtitle: "Kerala Green Cardamom Pods",
    category: "Whole Spices",
    price: 549,
    comparePrice: 699,
    currency: "INR",
    description:
      "Plucked from the misty hills of Idukki, Kerala, our ELAICHI pods are bold, plump, and intensely aromatic. Crack one open and you'll find jet-black seeds bursting with eucalyptus-like freshness and a sweet, floral warmth that defines chai, kheer, and biryani.",
    images: {
      jar: "/images/products/elaichi.png",
      pouch: "/images/products/elaichi-pouch.png",
    },
    image: "/images/products/elaichi.png",
    variants: [
      { id: "var_05_jar_sm", label: "Jar · 25g", price: 299, packaging: "jar" },
      { id: "var_05_jar_md", label: "Jar · 50g", price: 549, packaging: "jar" },
      { id: "var_05_jar_lg", label: "Jar · 100g", price: 999, packaging: "jar" },
      { id: "var_05_pouch_sm", label: "Pouch · 25g", price: 179, packaging: "pouch" },
      { id: "var_05_pouch_md", label: "Pouch · 50g", price: 329, packaging: "pouch" },
      { id: "var_05_pouch_lg", label: "Pouch · 100g", price: 599, packaging: "pouch" },
    ],
    origin: "Idukki, Kerala",
    usage:
      "Crush lightly and add to chai, biryani, kheer, or sweets. Chew a pod after meals as a natural mouth freshener and digestive aid.",
    storage:
      "Store whole pods in the sealed glass jar. Cardamom retains its potency best when kept whole and ground fresh before use.",
    tags: ["new"],
    weight: "50g",
  },
  {
    id: "prod_06",
    handle: "dal-chini",
    name: "DAL CHINI",
    subtitle: "Ceylon Cinnamon Sticks",
    category: "Whole Spices",
    price: 449,
    comparePrice: null,
    currency: "INR",
    description:
      "True Ceylon cinnamon — not the harsh cassia commonly sold. Our DAL CHINI quills are paper-thin, delicately sweet, and carry a complex warmth that pairs beautifully with both savoury dishes and desserts. Each stick unrolls in layers, releasing a refined, citrusy fragrance.",
    images: {
      jar: "/images/products/dal-chini.png",
      pouch: "/images/products/dal-chini-pouch.png",
    },
    image: "/images/products/dal-chini.png",
    variants: [
      { id: "var_06_jar_sm", label: "Jar · 50g", price: 249, packaging: "jar" },
      { id: "var_06_jar_md", label: "Jar · 100g", price: 449, packaging: "jar" },
      { id: "var_06_jar_lg", label: "Jar · 200g", price: 799, packaging: "jar" },
      { id: "var_06_pouch_sm", label: "Pouch · 50g", price: 149, packaging: "pouch" },
      { id: "var_06_pouch_md", label: "Pouch · 100g", price: 269, packaging: "pouch" },
      { id: "var_06_pouch_lg", label: "Pouch · 200g", price: 479, packaging: "pouch" },
    ],
    origin: "Sri Lanka (via Kerala)",
    usage:
      "Add whole sticks to rice, curries, and biryanis while cooking. Infuse in milk for cinnamon tea. Snap and add to overnight oats or baking.",
    storage:
      "Keep sealed in the glass jar in a cool, dry pantry. Cinnamon sticks maintain flavour for up to 2 years when stored properly.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_07",
    handle: "kali-mirch",
    name: "KALI MIRCH",
    subtitle: "Malabar Black Peppercorns",
    category: "Whole Spices",
    price: 279,
    comparePrice: null,
    currency: "INR",
    description:
      "Bold, pungent, and deeply aromatic — our KALI MIRCH comes from the Malabar coast of Kerala, the original homeland of black pepper. Known as 'Black Gold' for centuries, these peppercorns deliver a sharp, piney bite and a lingering warmth that awakens any dish.",
    images: {
      jar: "/images/products/kali-mirch.png",
      pouch: "/images/products/kali-mirch-pouch.png",
    },
    image: "/images/products/kali-mirch.png",
    variants: [
      { id: "var_07_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_07_jar_md", label: "Jar · 100g", price: 279, packaging: "jar" },
      { id: "var_07_jar_lg", label: "Jar · 250g", price: 599, packaging: "jar" },
      { id: "var_07_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_07_pouch_md", label: "Pouch · 100g", price: 159, packaging: "pouch" },
      { id: "var_07_pouch_lg", label: "Pouch · 250g", price: 359, packaging: "pouch" },
    ],
    origin: "Malabar, Kerala",
    usage:
      "Freshly crack over finished dishes for maximum flavour. Add whole peppercorns to stocks, marinades, and pickles. Pair with turmeric for enhanced bioavailability.",
    storage:
      "Store whole peppercorns in the sealed jar. Grind fresh before use — pre-ground pepper loses its essential oils rapidly.",
    tags: ["bestseller"],
    weight: "100g",
  },
  {
    id: "prod_08",
    handle: "jeera",
    name: "JEERA",
    subtitle: "Rajasthani Cumin Seeds",
    category: "Whole Spices",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "Sun-dried in the arid deserts of Rajasthan, our JEERA carries an earthy, nutty warmth that is the opening note of countless Indian dishes. These seeds are carefully cleaned and graded — plump, uniform, and packed with volatile oils that bloom the moment they hit hot oil.",
    images: {
      jar: "/images/products/jeera.png",
      pouch: "/images/products/jeera-pouch.png",
    },
    image: "/images/products/jeera.png",
    variants: [
      { id: "var_08_jar_sm", label: "Jar · 50g", price: 109, packaging: "jar" },
      { id: "var_08_jar_md", label: "Jar · 100g", price: 199, packaging: "jar" },
      { id: "var_08_jar_lg", label: "Jar · 250g", price: 429, packaging: "jar" },
      { id: "var_08_pouch_sm", label: "Pouch · 50g", price: 69, packaging: "pouch" },
      { id: "var_08_pouch_md", label: "Pouch · 100g", price: 119, packaging: "pouch" },
      { id: "var_08_pouch_lg", label: "Pouch · 250g", price: 259, packaging: "pouch" },
    ],
    origin: "Jodhpur, Rajasthan",
    usage:
      "Temper in hot oil or ghee until they crackle — the foundation of dals, rice, and vegetable dishes. Dry-roast and grind for chaat masala and raitas.",
    storage:
      "Store in the sealed glass jar away from heat and moisture. Cumin seeds maintain freshness for up to 12 months.",
    tags: [],
    weight: "100g",
  },

  // ===== NEW PRODUCTS =====
  {
    id: "prod_09",
    handle: "sugandhraj",
    name: "SUGANDHRAJ",
    subtitle: "Allspice Berries",
    category: "Whole Spices",
    price: 349,
    comparePrice: null,
    currency: "INR",
    description:
      "The warmth of a thousand kitchens in a single berry. SUGANDHRAJ captures the aromatic essence of cinnamon, clove, and nutmeg — all in one tiny, potent berry. Handpicked and sun-dried for maximum oil retention, these allspice berries bring complex depth to slow-cooked gravies, baking, and festive preparations.",
    images: {
      jar: "/images/products/sugandhraj.png",
      pouch: "/images/products/sugandhraj-pouch.png",
    },
    image: "/images/products/sugandhraj.png",
    variants: [
      { id: "var_09_jar_sm", label: "Jar · 50g", price: 199, packaging: "jar" },
      { id: "var_09_jar_md", label: "Jar · 100g", price: 349, packaging: "jar" },
      { id: "var_09_jar_lg", label: "Jar · 200g", price: 649, packaging: "jar" },
      { id: "var_09_pouch_sm", label: "Pouch · 50g", price: 119, packaging: "pouch" },
      { id: "var_09_pouch_md", label: "Pouch · 100g", price: 199, packaging: "pouch" },
      { id: "var_09_pouch_lg", label: "Pouch · 200g", price: 389, packaging: "pouch" },
    ],
    origin: "Kerala, India",
    usage: "Lightly crush before adding to marinades, curries, or baked goods. Pairs beautifully with root vegetables and slow-cooked meats.",
    storage: "Store whole berries in an airtight jar. Grind as needed to preserve the aromatic oils.",
    tags: ["new"],
    weight: "100g",
  },
  {
    id: "prod_10",
    handle: "tulsi-patta",
    name: "TULSI PATTA",
    subtitle: "Sweet Basil Leaves",
    category: "Dried Herbs",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Nature's aromatic masterpiece, air-dried to perfection. Our TULSI PATTA captures the sweet, peppery intensity of premium basil — a versatile herb that elevates Italian pastas, Thai curries, and fusion salads alike. Each leaf is carefully dried at low temperatures to lock in essential oils.",
    images: {
      jar: "/images/products/tulsi-patta.png",
      pouch: "/images/products/tulsi-patta-pouch.png",
    },
    image: "/images/products/tulsi-patta.png",
    variants: [
      { id: "var_10_jar_sm", label: "Jar · 25g", price: 149, packaging: "jar" },
      { id: "var_10_jar_md", label: "Jar · 50g", price: 249, packaging: "jar" },
      { id: "var_10_jar_lg", label: "Jar · 100g", price: 449, packaging: "jar" },
      { id: "var_10_pouch_sm", label: "Pouch · 25g", price: 89, packaging: "pouch" },
      { id: "var_10_pouch_md", label: "Pouch · 50g", price: 149, packaging: "pouch" },
      { id: "var_10_pouch_lg", label: "Pouch · 100g", price: 269, packaging: "pouch" },
    ],
    origin: "Nilgiri Hills, Tamil Nadu",
    usage: "Sprinkle over finished pasta, pizza, or salads. Infuse in olive oil for a fragrant dipping sauce. Add to tomato-based curries in the last 2 minutes.",
    storage: "Store in a cool, dark place. Dried basil retains flavour best when kept away from heat and moisture.",
    tags: [],
    weight: "50g",
  },
  {
    id: "prod_11",
    handle: "tej-patta",
    name: "TEJ PATTA",
    subtitle: "Indian Bay Leaves",
    category: "Dried Herbs",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "The secret to a fragrant base. Our TEJ PATTA leaves are slowly sun-dried to preserve their deep, herbal oils and distinctive cinnamon-clove aroma. A single leaf infuses your biryanis, dals, and stews with an earthy, regal fragrance that forms the aromatic backbone of Indian cuisine.",
    images: {
      jar: "/images/products/tej-patta.png",
      pouch: "/images/products/tej-patta-pouch.png",
    },
    image: "/images/products/tej-patta.png",
    variants: [
      { id: "var_11_jar_sm", label: "Jar · 25g", price: 119, packaging: "jar" },
      { id: "var_11_jar_md", label: "Jar · 50g", price: 199, packaging: "jar" },
      { id: "var_11_jar_lg", label: "Jar · 100g", price: 349, packaging: "jar" },
      { id: "var_11_pouch_sm", label: "Pouch · 25g", price: 69, packaging: "pouch" },
      { id: "var_11_pouch_md", label: "Pouch · 50g", price: 119, packaging: "pouch" },
      { id: "var_11_pouch_lg", label: "Pouch · 100g", price: 209, packaging: "pouch" },
    ],
    origin: "Uttarakhand, India",
    usage: "Add 1-2 leaves to your tadka for dals, or drop into rice while cooking. Essential in biryani, korma, and pulao preparations.",
    storage: "Store in a dry, airtight container. Bay leaves keep their potency for up to 2 years.",
    tags: [],
    weight: "50g",
  },
  {
    id: "prod_12",
    handle: "kala-til",
    name: "KALA TIL",
    subtitle: "Black Sesame Seeds",
    category: "Seeds & Nuts",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Rich, nutty, and visually striking. KALA TIL black sesame seeds are prized in Ayurveda for their mineral density and warming properties. These tiny powerhouses add dramatic contrast and a deep, toasted flavour to salads, breads, sushi, and traditional laddoos.",
    images: {
      jar: "/images/products/kala-til.png",
      pouch: "/images/products/kala-til-pouch.png",
    },
    image: "/images/products/kala-til.png",
    variants: [
      { id: "var_12_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_12_jar_md", label: "Jar · 100g", price: 249, packaging: "jar" },
      { id: "var_12_jar_lg", label: "Jar · 250g", price: 549, packaging: "jar" },
      { id: "var_12_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_12_pouch_md", label: "Pouch · 100g", price: 149, packaging: "pouch" },
      { id: "var_12_pouch_lg", label: "Pouch · 250g", price: 329, packaging: "pouch" },
    ],
    origin: "Gujarat, India",
    usage: "Toast lightly in a dry pan before sprinkling over salads, bowls, or breads. Essential in til laddoo and chikki.",
    storage: "Store in an airtight container in a cool place. Seeds can go rancid — use within 6 months of opening.",
    tags: ["new"],
    weight: "100g",
  },
  {
    id: "prod_13",
    handle: "shahjeera",
    name: "SHAHJEERA",
    subtitle: "Caraway Seeds",
    category: "Whole Spices",
    price: 299,
    comparePrice: null,
    currency: "INR",
    description:
      "Subtly nutty, intensely bold. SHAHJEERA — the 'royal cumin' — carries a sharp, anise-like complexity that sets it apart from ordinary cumin. These slender, crescent-shaped seeds are a prized ingredient in Kashmiri pulao, Mughlai gravies, and artisan breads.",
    images: {
      jar: "/images/products/shahjeera.png",
      pouch: "/images/products/shahjeera-pouch.png",
    },
    image: "/images/products/shahjeera.png",
    variants: [
      { id: "var_13_jar_sm", label: "Jar · 50g", price: 179, packaging: "jar" },
      { id: "var_13_jar_md", label: "Jar · 100g", price: 299, packaging: "jar" },
      { id: "var_13_jar_lg", label: "Jar · 200g", price: 549, packaging: "jar" },
      { id: "var_13_pouch_sm", label: "Pouch · 50g", price: 109, packaging: "pouch" },
      { id: "var_13_pouch_md", label: "Pouch · 100g", price: 179, packaging: "pouch" },
      { id: "var_13_pouch_lg", label: "Pouch · 200g", price: 329, packaging: "pouch" },
    ],
    origin: "Kashmir, India",
    usage: "Temper in ghee for Kashmiri pulao. Add to breads, sauerkraut, and cheese preparations for a warm, aromatic depth.",
    storage: "Store in a sealed glass jar away from moisture. Retains potency for up to 18 months.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_14",
    handle: "dhaniya",
    name: "DHANIYA",
    subtitle: "Ground Coriander Powder",
    category: "Ground Spices",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "The unsung hero of Indian cooking. Our DHANIYA is stone-ground from plump, aromatic coriander seeds sourced from Rajasthan. It lends a warm, citrusy sweetness that binds and balances every spice blend — the foundation of virtually every Indian gravy, dry sabzi, and chutney.",
    images: {
      jar: "/images/products/dhaniya.png",
      pouch: "/images/products/dhaniya-pouch.png",
    },
    image: "/images/products/dhaniya.png",
    variants: [
      { id: "var_14_jar_sm", label: "Jar · 50g", price: 109, packaging: "jar" },
      { id: "var_14_jar_md", label: "Jar · 100g", price: 199, packaging: "jar" },
      { id: "var_14_jar_lg", label: "Jar · 250g", price: 429, packaging: "jar" },
      { id: "var_14_pouch_sm", label: "Pouch · 50g", price: 69, packaging: "pouch" },
      { id: "var_14_pouch_md", label: "Pouch · 100g", price: 119, packaging: "pouch" },
      { id: "var_14_pouch_lg", label: "Pouch · 250g", price: 259, packaging: "pouch" },
    ],
    origin: "Kota, Rajasthan",
    usage: "The base of every curry. Mix with turmeric and chilli powder for the holy trinity of Indian gravies. Also great in marinades and chutneys.",
    storage: "Store in an airtight container. Ground coriander loses its aroma quickly — use within 4 months of opening.",
    tags: ["bestseller"],
    weight: "100g",
  },
  {
    id: "prod_15",
    handle: "gandh-ras",
    name: "GANDH-RAS",
    subtitle: "Dried Chives",
    category: "Dried Herbs",
    price: 279,
    comparePrice: null,
    currency: "INR",
    description:
      "Delicate, onion-kissed, and effortlessly elegant. GANDH-RAS dried chives add a subtle allium sweetness and a pop of green to finished dishes. Air-dried in small batches to preserve their gentle flavour, these chives are the perfect garnish for soups, baked potatoes, and cream-based preparations.",
    images: {
      jar: "/images/products/gandh-ras.png",
      pouch: "/images/products/gandh-ras-pouch.png",
    },
    image: "/images/products/gandh-ras.png",
    variants: [
      { id: "var_15_jar_sm", label: "Jar · 15g", price: 169, packaging: "jar" },
      { id: "var_15_jar_md", label: "Jar · 30g", price: 279, packaging: "jar" },
      { id: "var_15_jar_lg", label: "Jar · 60g", price: 499, packaging: "jar" },
      { id: "var_15_pouch_sm", label: "Pouch · 15g", price: 99, packaging: "pouch" },
      { id: "var_15_pouch_md", label: "Pouch · 30g", price: 169, packaging: "pouch" },
      { id: "var_15_pouch_lg", label: "Pouch · 60g", price: 299, packaging: "pouch" },
    ],
    origin: "Himachal Pradesh, India",
    usage: "Sprinkle over finished soups, scrambled eggs, or baked potatoes. Fold into cream cheese for a quick dip.",
    storage: "Store in a cool, dry place. Use within 6 months of opening for best flavour.",
    tags: [],
    weight: "30g",
  },
  {
    id: "prod_16",
    handle: "laung",
    name: "LAUNG",
    subtitle: "Premium Whole Cloves",
    category: "Whole Spices",
    price: 399,
    comparePrice: null,
    currency: "INR",
    description:
      "Intensely aromatic and warmly numbing. Our LAUNG cloves are handpicked from the spice gardens of Kerala — each bud packed with eugenol, the compound responsible for that unmistakable, dentist-defying bite. An essential in biryani masala, chai, and festive pickles.",
    images: {
      jar: "/images/products/laung.png",
      pouch: "/images/products/laung-pouch.png",
    },
    image: "/images/products/laung.png",
    variants: [
      { id: "var_16_jar_sm", label: "Jar · 25g", price: 229, packaging: "jar" },
      { id: "var_16_jar_md", label: "Jar · 50g", price: 399, packaging: "jar" },
      { id: "var_16_jar_lg", label: "Jar · 100g", price: 749, packaging: "jar" },
      { id: "var_16_pouch_sm", label: "Pouch · 25g", price: 139, packaging: "pouch" },
      { id: "var_16_pouch_md", label: "Pouch · 50g", price: 249, packaging: "pouch" },
      { id: "var_16_pouch_lg", label: "Pouch · 100g", price: 449, packaging: "pouch" },
    ],
    origin: "Kanyakumari, Kerala",
    usage: "Add 2-3 cloves to chai, biryani, or stock. Stud an onion with cloves for a classic European stock base. Chew a clove for toothache relief.",
    storage: "Store whole cloves in an airtight container. They retain potency for up to 3 years.",
    tags: ["new"],
    weight: "50g",
  },
  {
    id: "prod_17",
    handle: "kakaiya",
    name: "KAKAIYA",
    subtitle: "Natural Cocoa Powder",
    category: "Wellness Herbs",
    price: 449,
    comparePrice: null,
    currency: "INR",
    description:
      "Deep, decadent, and velvety smooth. KAKAIYA is crafted from single-origin cacao beans, cold-pressed to preserve the natural antioxidants and complex chocolate notes. Whether for a rich hot cocoa, indulgent baking, or a protein smoothie boost — expect unparalleled depth in every spoonful.",
    images: {
      jar: "/images/products/kakaiya.png",
      pouch: "/images/products/kakaiya-pouch.png",
    },
    image: "/images/products/kakaiya.png",
    variants: [
      { id: "var_17_jar_sm", label: "Jar · 50g", price: 269, packaging: "jar" },
      { id: "var_17_jar_md", label: "Jar · 100g", price: 449, packaging: "jar" },
      { id: "var_17_jar_lg", label: "Jar · 250g", price: 999, packaging: "jar" },
      { id: "var_17_pouch_sm", label: "Pouch · 50g", price: 159, packaging: "pouch" },
      { id: "var_17_pouch_md", label: "Pouch · 100g", price: 279, packaging: "pouch" },
      { id: "var_17_pouch_lg", label: "Pouch · 250g", price: 599, packaging: "pouch" },
    ],
    origin: "Idukki, Kerala",
    usage: "Sift into batter for cakes, brownies, and cookies. Whisk with hot milk for artisanal hot chocolate. Add to smoothie bowls for an antioxidant boost.",
    storage: "Store in a cool, dry, airtight container. Cocoa absorbs odours — keep away from strong-smelling spices.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_18",
    handle: "mirch-koot",
    name: "MIRCH KOOT",
    subtitle: "Crushed Red Pepper Flakes",
    category: "Ground Spices",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Bring the heat with precision. MIRCH KOOT is a vibrant blend of sun-dried red chillies, coarsely crushed to deliver a clean, spirited spice that lingers just long enough. Perfect for that signature kick on pizza, pasta, stir-fries, and everything that needs waking up.",
    images: {
      jar: "/images/products/mirch-koot.png",
      pouch: "/images/products/mirch-koot-pouch.png",
    },
    image: "/images/products/mirch-koot.png",
    variants: [
      { id: "var_18_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_18_jar_md", label: "Jar · 100g", price: 249, packaging: "jar" },
      { id: "var_18_jar_lg", label: "Jar · 250g", price: 549, packaging: "jar" },
      { id: "var_18_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_18_pouch_md", label: "Pouch · 100g", price: 149, packaging: "pouch" },
      { id: "var_18_pouch_lg", label: "Pouch · 250g", price: 329, packaging: "pouch" },
    ],
    origin: "Guntur, Andhra Pradesh",
    usage: "Sprinkle over pizza, pasta, noodles, or roasted meats. Add to stir-fries for a quick burst of heat. Mix into infused olive oils.",
    storage: "Store in a dry, airtight jar. Crushed peppers retain heat for up to 12 months.",
    tags: ["new"],
    weight: "100g",
  },
  {
    id: "prod_19",
    handle: "masala-raja",
    name: "MASALA RAJA",
    subtitle: "Curry Powder Blend",
    category: "Spice Blends",
    price: 299,
    comparePrice: null,
    currency: "INR",
    description:
      "The king of everyday cooking. MASALA RAJA is our signature curry powder — a harmonious blend of turmeric, coriander, cumin, fenugreek, and chilli, roasted and ground to create a versatile, ready-to-use spice mix. One spoonful transforms vegetables, lentils, and proteins into deeply flavourful meals.",
    images: {
      jar: "/images/products/masala-raja.png",
      pouch: "/images/products/masala-raja-pouch.png",
    },
    image: "/images/products/masala-raja.png",
    variants: [
      { id: "var_19_jar_sm", label: "Jar · 50g", price: 169, packaging: "jar" },
      { id: "var_19_jar_md", label: "Jar · 100g", price: 299, packaging: "jar" },
      { id: "var_19_jar_lg", label: "Jar · 250g", price: 649, packaging: "jar" },
      { id: "var_19_pouch_sm", label: "Pouch · 50g", price: 99, packaging: "pouch" },
      { id: "var_19_pouch_md", label: "Pouch · 100g", price: 179, packaging: "pouch" },
      { id: "var_19_pouch_lg", label: "Pouch · 250g", price: 389, packaging: "pouch" },
    ],
    origin: "Chennai, Tamil Nadu",
    usage: "Use as an all-purpose curry base. Add 1-2 teaspoons to oil before adding vegetables. Great in fried rice, curries, and marinades.",
    storage: "Store in an airtight container. Best used within 3-4 months of opening for peak flavour.",
    tags: ["bestseller"],
    weight: "100g",
  },
  {
    id: "prod_20",
    handle: "soya-patti",
    name: "SOYA PATTI",
    subtitle: "Dill Leaves & Seeds",
    category: "Dried Herbs",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Capture the essence of spring. SOYA PATTI features delicately air-dried dill — vibrant, herbaceous, and tangy. This classic herb adds a bright, refreshing finish to raitas, potato preparations, pickles, and grilled fish. A pantry essential for those who appreciate clean, green flavour.",
    images: {
      jar: "/images/products/soya-patti.png",
      pouch: "/images/products/soya-patti-pouch.png",
    },
    image: "/images/products/soya-patti.png",
    variants: [
      { id: "var_20_jar_sm", label: "Jar · 20g", price: 149, packaging: "jar" },
      { id: "var_20_jar_md", label: "Jar · 40g", price: 249, packaging: "jar" },
      { id: "var_20_jar_lg", label: "Jar · 80g", price: 449, packaging: "jar" },
      { id: "var_20_pouch_sm", label: "Pouch · 20g", price: 89, packaging: "pouch" },
      { id: "var_20_pouch_md", label: "Pouch · 40g", price: 149, packaging: "pouch" },
      { id: "var_20_pouch_lg", label: "Pouch · 80g", price: 269, packaging: "pouch" },
    ],
    origin: "Punjab, India",
    usage: "Fold into raita, yogurt dips, or potato salads. Sprinkle over grilled fish and roasted vegetables in the last minute of cooking.",
    storage: "Store in a cool, dry place away from sunlight. Use within 4 months for best flavour.",
    tags: [],
    weight: "40g",
  },
  {
    id: "prod_21",
    handle: "saunf",
    name: "SAUNF",
    subtitle: "Lucknowi Fennel Seeds",
    category: "Whole Spices",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "A sweet, licorice-kissed breath of freshness. Our SAUNF fennel seeds are sourced from Gujarat's finest farms — plump, green, and bursting with aromatic sweetness. A post-meal tradition, a digestive aid, and a versatile spice that bridges sweet and savoury cooking with effortless grace.",
    images: {
      jar: "/images/products/saunf.png",
      pouch: "/images/products/saunf-pouch.png",
    },
    image: "/images/products/saunf.png",
    variants: [
      { id: "var_21_jar_sm", label: "Jar · 50g", price: 109, packaging: "jar" },
      { id: "var_21_jar_md", label: "Jar · 100g", price: 199, packaging: "jar" },
      { id: "var_21_jar_lg", label: "Jar · 250g", price: 429, packaging: "jar" },
      { id: "var_21_pouch_sm", label: "Pouch · 50g", price: 69, packaging: "pouch" },
      { id: "var_21_pouch_md", label: "Pouch · 100g", price: 119, packaging: "pouch" },
      { id: "var_21_pouch_lg", label: "Pouch · 250g", price: 259, packaging: "pouch" },
    ],
    origin: "Unjha, Gujarat",
    usage: "Chew after meals as a natural mouth freshener. Add to fish curries, pickles, and Bengali sweets. Dry-roast and crush for panch phoron.",
    storage: "Store in an airtight jar away from moisture. Fennel seeds keep well for up to 2 years.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_22",
    handle: "lehsun-bhari",
    name: "LEHSUN BHARI",
    subtitle: "Garlic Powder",
    category: "Ground Spices",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Pure, potent garlic without the prep. LEHSUN BHARI is finely milled from sun-dried, high-quality garlic cloves — offering a smooth, savory depth and an unmistakable pungent aroma. The secret ingredient for instant flavour in marinades, rubs, dressings, and quick weeknight meals.",
    images: {
      jar: "/images/products/lehsun-bhari.png",
      pouch: "/images/products/lehsun-bhari-pouch.png",
    },
    image: "/images/products/lehsun-bhari.png",
    variants: [
      { id: "var_22_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_22_jar_md", label: "Jar · 100g", price: 249, packaging: "jar" },
      { id: "var_22_jar_lg", label: "Jar · 250g", price: 549, packaging: "jar" },
      { id: "var_22_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_22_pouch_md", label: "Pouch · 100g", price: 149, packaging: "pouch" },
      { id: "var_22_pouch_lg", label: "Pouch · 250g", price: 329, packaging: "pouch" },
    ],
    origin: "Madhya Pradesh, India",
    usage: "Add to marinades, soups, and stir-fries. Mix with butter for instant garlic bread. Use as a quick substitute when fresh garlic isn't available.",
    storage: "Store in a tightly sealed jar. Garlic powder absorbs moisture easily — keep completely dry.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_23",
    handle: "adrak-sondhi",
    name: "ADRAK SONDHI",
    subtitle: "Ginger Powder",
    category: "Ground Spices",
    price: 279,
    comparePrice: null,
    currency: "INR",
    description:
      "Zesty, warming, and brilliantly fragrant. ADRAK SONDHI brings a sophisticated heat and invigorating zing to both sweet and savoury creations. From golden curries and chai masala to spiced baked goods and wellness tonics — this finely ground ginger is a kitchen and medicine cabinet essential.",
    images: {
      jar: "/images/products/adrak-sondhi.png",
      pouch: "/images/products/adrak-sondhi-pouch.png",
    },
    image: "/images/products/adrak-sondhi.png",
    variants: [
      { id: "var_23_jar_sm", label: "Jar · 50g", price: 169, packaging: "jar" },
      { id: "var_23_jar_md", label: "Jar · 100g", price: 279, packaging: "jar" },
      { id: "var_23_jar_lg", label: "Jar · 250g", price: 599, packaging: "jar" },
      { id: "var_23_pouch_sm", label: "Pouch · 50g", price: 99, packaging: "pouch" },
      { id: "var_23_pouch_md", label: "Pouch · 100g", price: 169, packaging: "pouch" },
      { id: "var_23_pouch_lg", label: "Pouch · 250g", price: 359, packaging: "pouch" },
    ],
    origin: "Cochin, Kerala",
    usage: "Mix into chai, golden milk, or ginger ale. Add to curry bases, stir-fries, and baking. A pinch in warm water with honey makes a soothing tonic.",
    storage: "Store in an airtight container away from heat and moisture. Use within 6 months for maximum potency.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_24",
    handle: "jaiphal",
    name: "JAIPHAL",
    subtitle: "Whole Nutmeg",
    category: "Whole Spices",
    price: 499,
    comparePrice: null,
    currency: "INR",
    description:
      "Grated luxury. Our JAIPHAL nutmegs are sourced from Kerala's spice estates — each nut intensely warm, woody, and slightly sweet. A single grate elevates everything from creamy béchamel and traditional Indian desserts to masala chai and festive biryanis. The hallmark of refined cooking.",
    images: {
      jar: "/images/products/jaiphal.png",
      pouch: "/images/products/jaiphal-pouch.png",
    },
    image: "/images/products/jaiphal.png",
    variants: [
      { id: "var_24_jar_sm", label: "Jar · 25g", price: 299, packaging: "jar" },
      { id: "var_24_jar_md", label: "Jar · 50g", price: 499, packaging: "jar" },
      { id: "var_24_jar_lg", label: "Jar · 100g", price: 899, packaging: "jar" },
      { id: "var_24_pouch_sm", label: "Pouch · 25g", price: 179, packaging: "pouch" },
      { id: "var_24_pouch_md", label: "Pouch · 50g", price: 299, packaging: "pouch" },
      { id: "var_24_pouch_lg", label: "Pouch · 100g", price: 539, packaging: "pouch" },
    ],
    origin: "Thrissur, Kerala",
    usage: "Grate fresh over white sauces, desserts, and chai. A small amount goes a long way — start with a quarter teaspoon.",
    storage: "Store whole nutmegs in a sealed jar. They retain flavour for years. Always grate fresh.",
    tags: ["premium"],
    weight: "50g",
  },
  {
    id: "prod_25",
    handle: "pyaaz-dhool",
    name: "PYAAZ DHOOL",
    subtitle: "Onion Powder",
    category: "Ground Spices",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Deep, mellow sweetness concentrated into a fine powder. PYAAZ DHOOL delivers the savoury complexity of caramelized onions without the chopping or tears. An effortless way to add a gourmet foundation to soups, gravies, marinades, and spice rubs.",
    images: {
      jar: "/images/products/pyaaz-dhool.png",
      pouch: "/images/products/pyaaz-dhool-pouch.png",
    },
    image: "/images/products/pyaaz-dhool.png",
    variants: [
      { id: "var_25_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_25_jar_md", label: "Jar · 100g", price: 249, packaging: "jar" },
      { id: "var_25_jar_lg", label: "Jar · 250g", price: 549, packaging: "jar" },
      { id: "var_25_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_25_pouch_md", label: "Pouch · 100g", price: 149, packaging: "pouch" },
      { id: "var_25_pouch_lg", label: "Pouch · 250g", price: 329, packaging: "pouch" },
    ],
    origin: "Nashik, Maharashtra",
    usage: "Add to soups, gravies, and marinades for instant depth. Mix with garlic powder for a versatile all-purpose seasoning.",
    storage: "Store in a tightly sealed container. Onion powder clumps easily — keep completely dry.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_26",
    handle: "ajwain-patti",
    name: "AJWAIN PATTI",
    subtitle: "Dried Oregano Leaves",
    category: "Dried Herbs",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Bold, earthy, and intensely aromatic. AJWAIN PATTI delivers the robust flavour that defines Mediterranean and Indo-Italian cuisine. Harvested at peak potency, these dried oregano leaves bring a warm, slightly peppery bite that makes pizza, pasta, and grilled vegetables sing.",
    images: {
      jar: "/images/products/ajwain-patti.png",
      pouch: "/images/products/ajwain-patti-pouch.png",
    },
    image: "/images/products/ajwain-patti.png",
    variants: [
      { id: "var_26_jar_sm", label: "Jar · 25g", price: 149, packaging: "jar" },
      { id: "var_26_jar_md", label: "Jar · 50g", price: 249, packaging: "jar" },
      { id: "var_26_jar_lg", label: "Jar · 100g", price: 449, packaging: "jar" },
      { id: "var_26_pouch_sm", label: "Pouch · 25g", price: 89, packaging: "pouch" },
      { id: "var_26_pouch_md", label: "Pouch · 50g", price: 149, packaging: "pouch" },
      { id: "var_26_pouch_lg", label: "Pouch · 100g", price: 269, packaging: "pouch" },
    ],
    origin: "Himachal Pradesh, India",
    usage: "Sprinkle over pizza, bruschetta, and garlic bread. Add to tomato sauces and Italian-Indian fusion dishes.",
    storage: "Store in a cool, dry, airtight container. Dried oregano keeps well for up to 12 months.",
    tags: ["bestseller"],
    weight: "50g",
  },
  {
    id: "prod_27",
    handle: "deghi-rang",
    name: "DEGHI RANG",
    subtitle: "Premium Paprika Powder",
    category: "Ground Spices",
    price: 299,
    comparePrice: null,
    currency: "INR",
    description:
      "Vibrant colour, gentle soul. DEGHI RANG is sun-dried and carefully milled to provide a deep, sunset-red hue and a mild, sweet-smoky flavour. The secret behind tandoori's iconic colour and the finishing touch that defines gourmet seasoning. Pure colour, zero heat.",
    images: {
      jar: "/images/products/deghi-rang.png",
      pouch: "/images/products/deghi-rang-pouch.png",
    },
    image: "/images/products/deghi-rang.png",
    variants: [
      { id: "var_27_jar_sm", label: "Jar · 50g", price: 179, packaging: "jar" },
      { id: "var_27_jar_md", label: "Jar · 100g", price: 299, packaging: "jar" },
      { id: "var_27_jar_lg", label: "Jar · 250g", price: 649, packaging: "jar" },
      { id: "var_27_pouch_sm", label: "Pouch · 50g", price: 109, packaging: "pouch" },
      { id: "var_27_pouch_md", label: "Pouch · 100g", price: 179, packaging: "pouch" },
      { id: "var_27_pouch_lg", label: "Pouch · 250g", price: 389, packaging: "pouch" },
    ],
    origin: "Kashmir, India",
    usage: "Use for tandoori colour without the heat. Add to hummus, devilled eggs, and goulash. Essential in Spanish and Hungarian cuisine.",
    storage: "Store away from light — paprika fades quickly. Keep in a dark, cool, airtight container.",
    tags: ["new"],
    weight: "100g",
  },
  {
    id: "prod_28",
    handle: "hara-sookha",
    name: "HARA SOOKHA",
    subtitle: "Dried Parsley Flakes",
    category: "Dried Herbs",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "A bright, clean green finish for every plate. HARA SOOKHA dried parsley is gently air-dried to retain its verdant colour and mild, herbaceous freshness. The universal garnish that adds a professional, restaurant-quality touch to soups, pastas, roasted meats, and plated dishes.",
    images: {
      jar: "/images/products/hara-sookha.png",
      pouch: "/images/products/hara-sookha-pouch.png",
    },
    image: "/images/products/hara-sookha.png",
    variants: [
      { id: "var_28_jar_sm", label: "Jar · 20g", price: 149, packaging: "jar" },
      { id: "var_28_jar_md", label: "Jar · 40g", price: 249, packaging: "jar" },
      { id: "var_28_jar_lg", label: "Jar · 80g", price: 449, packaging: "jar" },
      { id: "var_28_pouch_sm", label: "Pouch · 20g", price: 89, packaging: "pouch" },
      { id: "var_28_pouch_md", label: "Pouch · 40g", price: 149, packaging: "pouch" },
      { id: "var_28_pouch_lg", label: "Pouch · 80g", price: 269, packaging: "pouch" },
    ],
    origin: "Ooty, Tamil Nadu",
    usage: "Sprinkle generously as a finishing garnish on soups, pastas, and roasted dishes. Mix into compound butter or herb crusts.",
    storage: "Store in a cool, dry, airtight container. Use within 6 months for the best colour and flavour.",
    tags: [],
    weight: "40g",
  },
  {
    id: "prod_29",
    handle: "khus-khus",
    name: "KHUS KHUS",
    subtitle: "White Poppy Seeds",
    category: "Seeds & Nuts",
    price: 349,
    comparePrice: null,
    currency: "INR",
    description:
      "Subtle, nutty, and elegantly textured. KHUS KHUS white poppy seeds add a delicate crunch and thickening quality to Indian curries, kormas, and pastes. Soaked and ground into a silky paste, they create the velvety base of Mughlai and Bengali cuisine's most refined dishes.",
    images: {
      jar: "/images/products/khus-khus.png",
      pouch: "/images/products/khus-khus-pouch.png",
    },
    image: "/images/products/khus-khus.png",
    variants: [
      { id: "var_29_jar_sm", label: "Jar · 50g", price: 199, packaging: "jar" },
      { id: "var_29_jar_md", label: "Jar · 100g", price: 349, packaging: "jar" },
      { id: "var_29_jar_lg", label: "Jar · 250g", price: 749, packaging: "jar" },
      { id: "var_29_pouch_sm", label: "Pouch · 50g", price: 119, packaging: "pouch" },
      { id: "var_29_pouch_md", label: "Pouch · 100g", price: 199, packaging: "pouch" },
      { id: "var_29_pouch_lg", label: "Pouch · 250g", price: 449, packaging: "pouch" },
    ],
    origin: "Rajasthan, India",
    usage: "Soak and grind into a paste for korma and shahi gravy bases. Sprinkle over naan and breads. Use in poppy seed laddoos and muffins.",
    storage: "Store in an airtight container in a cool place. Seeds can go rancid — best used within 4-6 months.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_30",
    handle: "gulmehendi",
    name: "GULMEHENDI",
    subtitle: "Dried Rosemary Leaves",
    category: "Dried Herbs",
    price: 279,
    comparePrice: null,
    currency: "INR",
    description:
      "An intense, piney woods awakening. GULMEHENDI rosemary is hand-harvested for maximum oil content — its needle-like leaves releasing a bold, herbaceous fragrance that pairs masterfully with roasted potatoes, grilled meats, artisan breads, and infused olive oils.",
    images: {
      jar: "/images/products/gulmehendi.png",
      pouch: "/images/products/gulmehendi-pouch.png",
    },
    image: "/images/products/gulmehendi.png",
    variants: [
      { id: "var_30_jar_sm", label: "Jar · 25g", price: 169, packaging: "jar" },
      { id: "var_30_jar_md", label: "Jar · 50g", price: 279, packaging: "jar" },
      { id: "var_30_jar_lg", label: "Jar · 100g", price: 499, packaging: "jar" },
      { id: "var_30_pouch_sm", label: "Pouch · 25g", price: 99, packaging: "pouch" },
      { id: "var_30_pouch_md", label: "Pouch · 50g", price: 169, packaging: "pouch" },
      { id: "var_30_pouch_lg", label: "Pouch · 100g", price: 299, packaging: "pouch" },
    ],
    origin: "Nilgiri Hills, Tamil Nadu",
    usage: "Add to roast potatoes, focaccia, and grilled lamb. Infuse in olive oil for a fragrant dipping sauce. Mix into bread dough.",
    storage: "Store in a sealed container away from light. Dried rosemary retains flavour well for up to 18 months.",
    tags: [],
    weight: "50g",
  },
  {
    id: "prod_31",
    handle: "tejbal",
    name: "TEJBAL",
    subtitle: "Dried Sage Leaves",
    category: "Dried Herbs",
    price: 279,
    comparePrice: null,
    currency: "INR",
    description:
      "Earthy, velvety, and deeply aromatic. TEJBAL sage leaves carry a slightly peppery, musky sophistication that brings depth to butter-based sauces, stuffings, and roasted meats. A herb that bridges European and Himalayan cuisines with quiet confidence.",
    images: {
      jar: "/images/products/tejbal.png",
      pouch: "/images/products/tejbal-pouch.png",
    },
    image: "/images/products/tejbal.png",
    variants: [
      { id: "var_31_jar_sm", label: "Jar · 20g", price: 169, packaging: "jar" },
      { id: "var_31_jar_md", label: "Jar · 40g", price: 279, packaging: "jar" },
      { id: "var_31_jar_lg", label: "Jar · 80g", price: 499, packaging: "jar" },
      { id: "var_31_pouch_sm", label: "Pouch · 20g", price: 99, packaging: "pouch" },
      { id: "var_31_pouch_md", label: "Pouch · 40g", price: 169, packaging: "pouch" },
      { id: "var_31_pouch_lg", label: "Pouch · 80g", price: 299, packaging: "pouch" },
    ],
    origin: "Uttarakhand, India",
    usage: "Add to brown butter for sage butter pasta. Mix into stuffings and sausage seasonings. Pairs beautifully with squash and sweet potato.",
    storage: "Store in an airtight container. Sage retains its potency for up to 12 months.",
    tags: [],
    weight: "40g",
  },
  {
    id: "prod_32",
    handle: "sendha-namak",
    name: "SENDHA NAMAK",
    subtitle: "Himalayan Pink Salt",
    category: "Salts & Seasoning",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "Harvested from ancient mineral deposits deep within the Himalayas, SENDHA NAMAK is a pure, unrefined gift from the earth. With its iconic rose hue and pristine mineral content, it provides a clean, balanced salinity that enhances the natural flavours of your ingredients. The finishing salt for the discerning cook.",
    images: {
      jar: "/images/products/sendha-namak.png",
      pouch: "/images/products/sendha-namak-pouch.png",
    },
    image: "/images/products/sendha-namak.png",
    variants: [
      { id: "var_32_jar_sm", label: "Jar · 100g", price: 119, packaging: "jar" },
      { id: "var_32_jar_md", label: "Jar · 250g", price: 199, packaging: "jar" },
      { id: "var_32_jar_lg", label: "Jar · 500g", price: 349, packaging: "jar" },
      { id: "var_32_pouch_sm", label: "Pouch · 100g", price: 69, packaging: "pouch" },
      { id: "var_32_pouch_md", label: "Pouch · 250g", price: 119, packaging: "pouch" },
      { id: "var_32_pouch_lg", label: "Pouch · 500g", price: 209, packaging: "pouch" },
    ],
    origin: "Khewra, Himalayan Region",
    usage: "Use as a finishing salt on salads, grilled meats, and chocolates. Essential during Navratri fasting. Dissolve in warm water for a mineral-rich gargle.",
    storage: "Store in a dry container. Pink salt is non-perishable and lasts indefinitely.",
    tags: ["new"],
    weight: "250g",
  },
  {
    id: "prod_33",
    handle: "safed-til",
    name: "SAFED TIL",
    subtitle: "White Sesame Seeds",
    category: "Seeds & Nuts",
    price: 199,
    comparePrice: null,
    currency: "INR",
    description:
      "Toasted or raw, SAFED TIL white sesame seeds offer a delicate nuttiness and satisfying crunch. These tiny pearls are a staple for garnishing stir-fries, topping breads, and adding a professional finishing touch to bowls, til laddoos, and tahini preparations.",
    images: {
      jar: "/images/products/safed-til.png",
      pouch: "/images/products/safed-til-pouch.png",
    },
    image: "/images/products/safed-til.png",
    variants: [
      { id: "var_33_jar_sm", label: "Jar · 50g", price: 109, packaging: "jar" },
      { id: "var_33_jar_md", label: "Jar · 100g", price: 199, packaging: "jar" },
      { id: "var_33_jar_lg", label: "Jar · 250g", price: 429, packaging: "jar" },
      { id: "var_33_pouch_sm", label: "Pouch · 50g", price: 69, packaging: "pouch" },
      { id: "var_33_pouch_md", label: "Pouch · 100g", price: 119, packaging: "pouch" },
      { id: "var_33_pouch_lg", label: "Pouch · 250g", price: 259, packaging: "pouch" },
    ],
    origin: "Gujarat, India",
    usage: "Toast lightly for maximum flavour. Sprinkle over sushi, stir-fries, and salads. Grind into tahini paste or mix into til laddoo and chikki.",
    storage: "Store in an airtight container in a cool place. Use within 6 months — sesame seeds can become rancid.",
    tags: [],
    weight: "100g",
  },
  {
    id: "prod_34",
    handle: "ajwain-phool",
    name: "AJWAIN PHOOL",
    subtitle: "Dried Thyme Leaves",
    category: "Dried Herbs",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "Small leaves, massive flavour. AJWAIN PHOOL thyme is earthy, floral, and subtly minty — the backbone of refined European and fusion cooking. These tiny leaves deliver a sophisticated, herbaceous warmth to roasted meats, vegetable gratins, and slow-simmered stews.",
    images: {
      jar: "/images/products/ajwain-phool.png",
      pouch: "/images/products/ajwain-phool-pouch.png",
    },
    image: "/images/products/ajwain-phool.png",
    variants: [
      { id: "var_34_jar_sm", label: "Jar · 20g", price: 149, packaging: "jar" },
      { id: "var_34_jar_md", label: "Jar · 40g", price: 249, packaging: "jar" },
      { id: "var_34_jar_lg", label: "Jar · 80g", price: 449, packaging: "jar" },
      { id: "var_34_pouch_sm", label: "Pouch · 20g", price: 89, packaging: "pouch" },
      { id: "var_34_pouch_md", label: "Pouch · 40g", price: 149, packaging: "pouch" },
      { id: "var_34_pouch_lg", label: "Pouch · 80g", price: 269, packaging: "pouch" },
    ],
    origin: "Himachal Pradesh, India",
    usage: "Add to roasted vegetables, grilled chicken, and hearty stews. Pairs beautifully with lemon, garlic, and olive oil.",
    storage: "Store in an airtight container away from light. Dried thyme keeps well for up to 12 months.",
    tags: [],
    weight: "40g",
  },
  {
    id: "prod_35",
    handle: "laal-tikha",
    name: "LAAL TIKHA",
    subtitle: "Chilli Powder (Extra Hot)",
    category: "Ground Spices",
    price: 249,
    comparePrice: null,
    currency: "INR",
    description:
      "For those who live for the burn. LAAL TIKHA is our extra-hot chilli powder — stone-ground from Guntur's fiercest Teja and Byadgi chillies. This is not for the faint-hearted. A vibrant orange-red powder that delivers searing heat, a smoky complexity, and the endorphin rush spice lovers crave.",
    images: {
      jar: "/images/products/laal-tikha.png",
      pouch: "/images/products/laal-tikha-pouch.png",
    },
    image: "/images/products/laal-tikha.png",
    variants: [
      { id: "var_35_jar_sm", label: "Jar · 50g", price: 149, packaging: "jar" },
      { id: "var_35_jar_md", label: "Jar · 100g", price: 249, packaging: "jar" },
      { id: "var_35_jar_lg", label: "Jar · 250g", price: 549, packaging: "jar" },
      { id: "var_35_pouch_sm", label: "Pouch · 50g", price: 89, packaging: "pouch" },
      { id: "var_35_pouch_md", label: "Pouch · 100g", price: 149, packaging: "pouch" },
      { id: "var_35_pouch_lg", label: "Pouch · 250g", price: 329, packaging: "pouch" },
    ],
    origin: "Guntur, Andhra Pradesh",
    usage: "Use sparingly — a quarter teaspoon packs serious heat. Perfect for vindaloo, schezwan, and fiery chutneys. Brave souls sprinkle over everything.",
    storage: "Store in a cool, dry, airtight container. Retains heat for up to 12 months.",
    tags: ["new"],
    weight: "100g",
  },
  {
    id: "prod_36",
    handle: "kali-laung",
    name: "KALI LAUNG",
    subtitle: "Black Cardamom Pods",
    category: "Whole Spices",
    price: 399,
    comparePrice: null,
    currency: "INR",
    description:
      "Smoky, bold, and hauntingly aromatic. KALI LAUNG black cardamom is dried over open flames, giving it a distinctive camphor-like smokiness that is the secret weapon of North Indian and Nepali cooking. Essential in garam masala, nihari, and rich, slow-cooked gravies.",
    images: {
      jar: "/images/products/kali-laung.png",
      pouch: "/images/products/kali-laung-pouch.png",
    },
    image: "/images/products/kali-laung.png",
    variants: [
      { id: "var_36_jar_sm", label: "Jar · 25g", price: 229, packaging: "jar" },
      { id: "var_36_jar_md", label: "Jar · 50g", price: 399, packaging: "jar" },
      { id: "var_36_jar_lg", label: "Jar · 100g", price: 749, packaging: "jar" },
      { id: "var_36_pouch_sm", label: "Pouch · 25g", price: 139, packaging: "pouch" },
      { id: "var_36_pouch_md", label: "Pouch · 50g", price: 249, packaging: "pouch" },
      { id: "var_36_pouch_lg", label: "Pouch · 100g", price: 449, packaging: "pouch" },
    ],
    origin: "Sikkim, Northeast India",
    usage: "Lightly crush and add to rice dishes, curries, and meat preparations. Use 1-2 pods per dish — the flavour is intense. Essential in garam masala.",
    storage: "Store whole pods in an airtight container. Black cardamom keeps well for up to 2 years.",
    tags: [],
    weight: "50g",
  },
  {
    id: "prod_37",
    handle: "sabut-mirch",
    name: "SABUT MIRCH",
    subtitle: "Whole Red Chilli (Mathania)",
    category: "Whole Spices",
    price: 299,
    comparePrice: null,
    currency: "INR",
    description:
      "The crown jewel of Rajasthani cuisine. Our SABUT MIRCH Mathania chillies are sun-dried whole — deep red, moderately hot, and packed with a fruity, smoky sweetness that defines laal maas, ker sangri, and Marwari cooking. Drop a few in hot oil and watch your kitchen come alive.",
    images: {
      jar: "/images/products/sabut-mirch.png",
      pouch: "/images/products/sabut-mirch-pouch.png",
    },
    image: "/images/products/sabut-mirch.png",
    variants: [
      { id: "var_37_jar_sm", label: "Jar · 50g", price: 179, packaging: "jar" },
      { id: "var_37_jar_md", label: "Jar · 100g", price: 299, packaging: "jar" },
      { id: "var_37_jar_lg", label: "Jar · 250g", price: 649, packaging: "jar" },
      { id: "var_37_pouch_sm", label: "Pouch · 50g", price: 109, packaging: "pouch" },
      { id: "var_37_pouch_md", label: "Pouch · 100g", price: 179, packaging: "pouch" },
      { id: "var_37_pouch_lg", label: "Pouch · 250g", price: 389, packaging: "pouch" },
    ],
    origin: "Mathania, Jodhpur, Rajasthan",
    usage: "Drop 2-3 whole chillies in hot oil for tempering dals and curries. Essential in Rajasthani laal maas. Remove before serving for flavour without excessive heat.",
    storage: "Store in a dry, airtight container. Whole dried chillies keep well for up to 18 months.",
    tags: [],
    weight: "100g",
  },
];

export const categories = [
  { id: "cat_01", name: "Whole Spices", handle: "whole-spices", count: 12 },
  { id: "cat_02", name: "Ground Spices", handle: "ground-spices", count: 9 },
  { id: "cat_03", name: "Dried Herbs", handle: "dried-herbs", count: 10 },
  { id: "cat_04", name: "Spice Blends", handle: "spice-blends", count: 2 },
  { id: "cat_05", name: "Wellness Herbs", handle: "wellness-herbs", count: 2 },
  { id: "cat_06", name: "Seeds & Nuts", handle: "seeds-nuts", count: 3 },
  { id: "cat_07", name: "Salts & Seasoning", handle: "salts-seasoning", count: 1 },
];

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    location: "Mumbai",
    text: "The KESAR DHAGA is unlike any saffron I've ever used. Three threads and my entire biryani turned golden. The glass jars are beautiful on my kitchen shelf.",
    rating: 5,
  },
  {
    id: 2,
    name: "Arjun Mehta",
    location: "Delhi",
    text: "I switched to spicejar's HALDI GOLD for my morning golden milk and the difference is night and day. You can taste the curcumin richness. Never going back.",
    rating: 5,
  },
  {
    id: 3,
    name: "Meera Krishnan",
    location: "Bangalore",
    text: "Finally, a brand that treats spices with the reverence they deserve. The GARAM MASALA smells exactly like my grandmother's kitchen. Pure, honest spices.",
    rating: 5,
  },
  {
    id: 4,
    name: "Rohan Desai",
    location: "Pune",
    text: "Ordered the ELAICHI and DAL CHINI — both are incredibly fresh and aromatic. My chai has never tasted better. The pouch option is great for everyday use.",
    rating: 5,
  },
  {
    id: 5,
    name: "Ananya Iyer",
    location: "Chennai",
    text: "The MASALA RAJA curry powder is my weeknight saviour. One spoon and my dal transforms into something restaurant-worthy. Love the brand's transparency about sourcing.",
    rating: 5,
  },
];

export const uspItems = [
  {
    icon: "🌱",
    title: "Farm to Jar",
    text: "Sourced directly from Indian farms",
  },
  {
    icon: "🔬",
    title: "Lab Tested",
    text: "Every batch tested for purity",
  },
  {
    icon: "✋",
    title: "Hand Ground",
    text: "Traditional stone-ground process",
  },
  {
    icon: "♻️",
    title: "Glass Jars",
    text: "Sustainable, reusable packaging",
  },
];

export function formatPrice(amount, currency = "INR") {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function getProduct(handle) {
  return products.find((p) => p.handle === handle) || null;
}

export function getProductsByCategory(category) {
  if (!category || category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getProductsByCategoryHandle(handle) {
  if (!handle || handle === "all") return products;
  const cat = categories.find((c) => c.handle === handle);
  if (!cat) return products;
  return products.filter((p) => p.category === cat.name);
}

export function getProductsByTag(tag) {
  return products.filter((p) => p.tags.includes(tag));
}

export function getRelatedProducts(handle, limit = 4) {
  const product = getProduct(handle);
  if (!product) return [];
  const sameCategory = products.filter(
    (p) => p.handle !== handle && p.category === product.category
  );
  const otherCategory = products.filter(
    (p) => p.handle !== handle && p.category !== product.category
  );
  return [...sameCategory, ...otherCategory].slice(0, limit);
}

export function getVariantsByPackaging(product, packaging) {
  return product.variants.filter((v) => v.packaging === packaging);
}

export function getDefaultVariant(product, packaging = "jar") {
  const variants = getVariantsByPackaging(product, packaging);
  // Return the middle variant as default
  if (variants.length === 0) return product.variants[0];
  return variants[Math.floor(variants.length / 2)] || variants[0];
}
